source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'

# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# environmental variable managment
gem 'figaro'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# we do not current have a test environment
# group :development, :test do
#   # Call 'byebug' anywhere in the code to stop execution and get a debugger console
#   gem 'byebug', platform: :mri
# end

group :development do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # Need to remove readline errors in console
  gem 'rb-readline'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # gem 'wdm', '>= 0.1.0'

  # Rspec
  gem 'rspec-rails', '~> 3.8'
  gem 'rails-controller-testing'
  gem 'factory_bot_rails'
  # gem 'webmock'
  gem 'faker'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Front-end development requirements
gem 'bootstrap', '~> 4.1.1'
gem 'popper_js', '~> 1.12.9'
gem 'normalize-rails', '~> 4.1', '>= 4.1.1'
gem 'font-awesome-rails', '~> 4.7', '>= 4.7.0.4'
gem 'themify-icons-rails' , github: 'scratch-soft/themify-icons-rails'
gem 'nokogiri'
# gem 'webpacker', '>= 4.0.x'
# gem 'foreman'
gem 'active_model_serializers', '~> 0.10.0'
# gem 'httparty'

# Devise requirements
gem 'devise'

# Data file parsing
gem "roo", "~> 2.7.0"
gem 'rubyXL'
# gem "iconv", "~> 1.0.3"

# Job processing
gem 'daemons'
gem 'delayed_job_active_record'
gem 'progress_job'
gem "aws-sdk-s3", require: false

# Parses strings into dates and times
gem 'chronic'

# Google library for parsing phone numbers
gem 'phonelib'

# More advanced and asynchronous http requests
gem 'typhoeus'

# Use .env for storing secret environment variables
gem 'dotenv-rails'

# OAuth2 wrapping gem
gem 'oauth2'

# Sentry exception handler
gem 'sentry-raven'

ruby '2.5.3'